### ISSUE TITLE
[BUG] F5 clears data if data was loaded from json

### ISSUE THREAD

**Issue by sjvrijn** [ESI-FAR/INA-tool#110]
### Describe the bug
Session is cleared when refreshing the dashboard page, either through F5 or by visiting e.g. the Help page. This only occurs when data has been loaded from a json file.

### To Reproduce
1. Go to the dashboard
2. Click on 'upload file'
3. Select a previously created .json file
4. Press F5
5. See error: session is cleared

### Expected behavior
The session should be maintained after pressing F5. This correct behavior is still shown when uploading a csv file instead.

### Sample JSON file
[ina-demo.json](https://github.com/user-attachments/files/17012472/ina-demo.json)

**Comment by sjvrijn** [comment]
A possible solution could be #111

**Comment by ermannolocascio** [comment]
Hi @sjvrijn , there should be some problem with this version as the download does not work here.

**Comment by sjvrijn** [comment]
@ermannolocascio Can you further explain what you mean? Which download functionality does not work and how is that related to this issue?

**Comment by sjvrijn** [comment]
Both the table and image are no longer lost on refreshing with F5 since #103, so I'm closing this issue.
