### ISSUE TITLE
Edge drawn to Polygon does not connect properly

### ISSUE THREAD

**Issue by sjvrijn** [ESI-FAR/INA-tool#25]
The edge to the activation conditions (hexagon polygon element) does not connect properly, but terminates somewhere above the shape. When moving the shape, the position it 'connects' to floats even further away from the actual shape..

It probably means we're doing something wrong with calculating where it should connect to. Solving this should include getting rid of the magic `offsetX/Y` values (https://github.com/ESI-FAR/INA-tool/pull/19/files#r1617226329)

![image](https://github.com/ESI-FAR/INA-tool/assets/8833517/12cf0bb9-3989-40f9-a6b5-ecf220f60b2f)

**Comment by ermannolocascio** [comment]
Closed with #32
