### ISSUE TITLE
Enables drawing connections between statements

### ISSUE THREAD

**Issue by ermannolocascio** [ESI-FAR/INA-tool#28]
to be clarified how this interaction happens, e.g. right click and add connection option.

Possible ref: https://stackoverflow.com/questions/50252070/svg-draw-connection-line-between-two-rectangles

**Comment by sjvrijn** [comment]
A simple suggestion would be to e.g. have three new buttons:
- draw green link
- draw red link
- draw purple link

If one of the 'draw <color> link' buttons is pressed, then the user should be able to click on a node from statement 1, and then on a node of a different statement 2. When the second node is clicked, the arrow of the specified color should be drawn between the clicked nodes.

Only one link should be drawn between two nodes, so if two nodes are selected with a different color, any existing link should be removed first.

It would also be good to have a way to remove a link.


See image below for reference:

![image](https://github.com/ESI-FAR/INA-tool/assets/8833517/e1109c08-5a5d-4680-be09-da8a1ad7e906)

**Comment by ermannolocascio** [comment]
Thank you! 
I'm not entirely sure that placing three buttons at the top is visually the best option. How about using a right-click context menu triggering a dropdown window containing the set of possible actions the user can do (draw line ... .etc)? 

E.g.

![image](https://github.com/ESI-FAR/INA-tool/assets/150127923/7a7cf156-b059-4431-afb0-37e818d284f0)

**Comment by sjvrijn** [comment]
Good idea, that looks much better indeed :+1:

**Comment by sjvrijn** [comment]
closed by #44
