### ISSUE TITLE
Scrollable window needed within the import modal to handle large csv file

### ISSUE THREAD

**Issue by ermannolocascio** [ESI-FAR/INA-tool#3]
Add a vertically scrollable window to handle large csv file with several number of rows. 

![image](https://github.com/ESI-FAR/INA-tool/assets/150127923/325ba2df-0471-4aa5-b65b-1ae93a985575)

**Comment by sjvrijn** [comment]
Closing this issue, as we decided to hide that information on file upload anyway.
