### ISSUE TITLE
BUG: Uploading csv with index creates double index and breaks render 

### ISSUE THREAD

**Issue by sjvrijn** [ESI-FAR/INA-tool#37]
When downloading a fresh CSV from the [template](https://nlesc.sharepoint.com/:x:/r/sites/esi-far77/_layouts/15/Doc.aspx?sourcedoc=%7Bdea5b2eb-0e40-4558-ba3e-9ba9acc8b792%7D&action=edit&wdenableroaming=1&wdfr=1&wdlcid=en-US&wdorigin=ItemsView&wdhostclicktime=1715869016578&wdredirectionreason=Force_SingleStepBoot&wdinitialsession=66d38ec2-ab7f-5753-296a-3ee7cf6a6fc3&wdrldsc=2&wdrldc=1&wdrldr=ServiceCreationTimedOut), Excel adds a row-index by default. Our tool does not check whether an index already exists, so it adds another one, which breaks the mapping between the values and expected column names. Especially the statement type is then not found, which means the nodes are rendered in black and you can't read the text.

**Comment by ermannolocascio** [comment]
Thank you for discovering it! 
I see it. I can try to work on it if it sound ok for you. 

![image](https://github.com/ESI-FAR/INA-tool/assets/150127923/764c11c1-037f-4e83-9f35-ef8b37e50ee7)
