### ISSUE TITLE
Increase font size

### ISSUE THREAD

**Issue by ermannolocascio** [ESI-FAR/INA-tool#71]
At the moment this resulted to be not very readable.

**Comment by ermannolocascio** [comment]
Following I made some renders of the flowchart with font at 10px (the original), 12px, 13px and 14px. 

Please, let us know which is the preferred one. Thank you :) 

10px ----------------------
![20240718-111711_Institutional_statement_template](https://github.com/user-attachments/assets/ed3faef7-a6b7-450e-9034-bc3d8fd29eda)

12px----------------------
![20240718-113426_Institutional_statement_template_12px](https://github.com/user-attachments/assets/bed960e4-3049-4d13-ae57-fc442406df80)

13px----------------------
![20240718-113537_Institutional_statement_template_13px](https://github.com/user-attachments/assets/ed587885-7338-461d-bd62-27a2197224c2)


14px----------------------
![20240718-114248_Institutional_statement_template_14px](https://github.com/user-attachments/assets/28cbaf7c-cd06-4826-ad10-76cdde39508f)

**Comment by aminehghorbani** [comment]
Dear Ermanno, in my view they are still not readable. Would it be possible to decrease the margin of the text in the shapes? Also maybe increase the space between the lines? When you make them bigger, they become more unreadable because the space between the lines become smaller

**Comment by ermannolocascio** [comment]
Thank you @aminehghorbani for your feedback. I'm trying to find a good compromise. How about this? The space between lines has been set to 1.25 and the margins are reduced (we reduce the text lenght for each line, this is how it works. Now it is set to 23 characters, before was 25). The font size now is 12px. Please, feel free to ask for changes. We can iterate it. If you prefer we do it via teams in call. 

![20240718-133306_Institutional_statement_template](https://github.com/user-attachments/assets/445587c5-26aa-4854-aba4-a58650e05814)

**Comment by aminehghorbani** [comment]
Thanks Ermanno for the new update. Its much better, but it's still not easy to copy/paste a diagram into a word file because it's still relatively unreadable. Can the text be fluid in the shape? I.e., depending on the amount of text, it changes sizes to fit the shape?  Reducing the margin might help further or not? and maybe a font other than the one you have can improve readability? But in general, it's much much better, so if it doesn't work it can be an acceptable solution for now.

**Comment by ermannolocascio** [comment]
Hi Amineh, 

the best thing we can do at this stage is to go for this compromise for now given that you need to be able to tune the font size depending on the statement text you upload. This would allows you to achieve the right render. I open an issue on this to be solved for the next future.
